services:
  tease:
    image: ghcr.io/ls1intum/tease:latest
    container_name: tease
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tease.rule=Host(`${SERVER_HOST}`) && PathPrefix(`/tease`)"
      - "traefik.http.middlewares.tease-stripprefix.stripprefix.prefixes=/tease"
      - "traefik.http.routers.tease.middlewares=tease-stripprefix"
      - "traefik.http.routers.tease.entrypoints=websecure"
      - "traefik.http.routers.tease.tls.certresolver=letsencrypt"
    expose:
      - "80"
    networks:
      - prompt-network

  tease-server:
    image: ghcr.io/ls1intum/tease-server:latest
    container_name: tease-server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tease-server.rule=Host(`${SERVER_HOST}`) && PathPrefix(`/ws`)"
      - "traefik.http.services.tease-server.loadbalancer.server.port=8081"
      - "traefik.http.routers.tease-server.entrypoints=websecure"
      - "traefik.http.routers.tease-server.tls.certresolver=letsencrypt"
      - "traefik.http.routers.tease-server.middlewares=jwt-middleware"
    expose:
      - "8081"
    networks:
      - prompt-network

networks:
  prompt-network:
    external: true
