name: Build and Push

on:
  pull_request:
  push:
    branches:
      - develop
      - main
    tags: '[0-9]+.[0-9]+.[0-9]+'
  release:
    types:
      - created
  workflow_call:
    outputs:
      image_tag:
        description: "The tag of the tease image that was built"
        value: "${{ jobs.buildx.outputs.result }}"

jobs:
  build-and-push:
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./client/Dockerfile
            image: ghcr.io/ls1intum/tease
          - dockerfile: ./server/Dockerfile
            image: ghcr.io/ls1intum/tease-server
    uses: ls1intum/.github/.github/workflows/build-and-push-docker-image.yml@main
    with:
      image-name: ${{ matrix.image }}
      docker-file: ${{ matrix.dockerfile }}
