name: Build and Push

on:
  pull_request:
  push:
    branches: 
    - develop
    - main
    tags: '[0-9]+.[0-9]+.[0-9]+'
  release:
    types:
    - created

jobs:
  buildx:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Compute Tag
        uses: actions/github-script@v6
        id: compute-tag
        with:
          result-encoding: string
          script: |
            if (context.eventName === "pull_request") {
              return "pr-" + context.issue.number;
            }
            if (context.eventName === "push") {
              if (context.ref.startsWith("refs/tags/")) {
                return context.ref.slice(10);
              }
              if (context.ref === "refs/heads/main") {
                return "latest";
              }
            }
            return "FALSE";

      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Login
        id: docker-login
        run: |
          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.compute-tag.outputs.result != 'FALSE' }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          version: latest

      - name: Build Image and Push to GitHub Container Registry and DockerHub
        uses: docker/build-push-action@v4
        if: ${{ steps.compute-tag.outputs.result != 'FALSE' }}
        with:
          context: .
          tags: |
            ls1tum/tease:${{ steps.compute-tag.outputs.result }}
            ghcr.io/ls1intum/tease:${{ steps.compute-tag.outputs.result }}
          platforms: linux/amd64,linux/arm64/v8
          push: true
