name: Build and Push

on:
  pull_request:
  # push:
  #   branches:
  #     - develop
  #     - main
  #   tags: "[0-9]+.[0-9]+.[0-9]+"
  # TODO: Design a release workflow
  release:
    types:
      - created
  workflow_call:

jobs:
  build-and-push:
    strategy:
      fail-fast: false
      matrix:
        include:
          - image-name: ls1intum/tease
            docker-file: ./client/Dockerfile
            docker-context: ./client
          - image-name: ls1intum/tease-server
            docker-file: ./server/Dockerfile
            docker-context: ./server
    uses: ls1intum/.github/.github/workflows/build-and-push-docker-image.yml@main
    with:
      image-name: ${{ matrix.image-name }}
      docker-file: ${{ matrix.docker-file }}
      docker-context: ${{ matrix.docker-context }}
