name: Build and Deploy to Prod

on:
  push:
    branches: [main]

jobs:
  build-prod-container:
    uses: ./.github/workflows/build-and-push.yml
    secrets: inherit
  deploy-prod-container:
    needs: build-prod-container
    uses: ./.github/workflows/deploy-docker.yml
    secrets: inherit
    with:
      environment: "PROMPT-Prod"
      tease_image_tag: "latest"
    