name: Build and Deploy to Dev

on:
  push:
    branches: [develop]

jobs:
  build-dev-container:
    uses: ./.github/workflows/build-and-push.yml
    secrets: inherit
  deploy-dev-container:
    needs: build-dev-container
    uses: ./.github/workflows/deploy-docker.yml
    secrets: inherit
    with:
      environment: PROMPT-Dev
      tease_image_tag: "develop"
    